production:
   email_address: smtp.gmail.com
   email_port: '587'
   email_domain: gmail.com
   email_user_name: opendsa.noreply@gmail.com
   email_password: ENV['EMAIL_PW']
   host_url: https://opendsa-server.cs.vt.edu/
   python_venv_path: '/home/deploy/OpenDSA/.pyVenv/bin/activate'
   opendsa_branch: 'master'
